# Copyright 2021 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

go_package(dependencies=[":embeds", ":testdata"])

resources(name="embeds", sources=["hello.txt"])
files(name="testdata", sources=["testdata/*"])
